
  create table "public"."addresses" (
    "address_id" integer not null,
    "latitude" numeric,
    "longitude" numeric,
    "user_id" integer,
    "salesman_id" integer,
    "vendor_id" integer,
    "customer_id" integer,
    "shipping_address" text default ''::text,
    "phone_number" text default ''::text,
    "postal_code" text default ''::text,
    "city" text default ''::text,
    "country" text default ''::text,
    "full_name" text not null,
    "place_id" text,
    "formatted_address" text
      );



  create table "public"."auth_sessions" (
    "session_id" character varying not null,
    "user_id" uuid,
    "status" character varying not null default 'pending'::character varying,
    "created_at" timestamp with time zone not null default now(),
    "expires_at" timestamp with time zone not null default (now() + '00:10:00'::interval)
      );



  create table "public"."brands" (
    "brandID" integer not null,
    "product_count" bigint not null default '0'::bigint,
    "isVerified" boolean default false,
    "isFeatured" boolean,
    "brandname" text
      );



  create table "public"."cart" (
    "cart_id" integer generated by default as identity not null,
    "quantity" text not null default ''::text,
    "customer_id" integer,
    "variant_id" integer
      );



  create table "public"."categories" (
    "category_id" integer not null,
    "isFeatured" boolean default false,
    "created_at" timestamp with time zone default now(),
    "category_name" text not null,
    "product_count" integer
      );



  create table "public"."customers" (
    "customer_id" integer not null,
    "auth_uid" character varying default auth.uid(),
    "email" text not null default ''::text,
    "cnic" text default ''::text,
    "last_name" text default ''::text,
    "phone_number" text default ''::text,
    "created_at" timestamp with time zone default now(),
    "first_name" text not null default ''::text,
    "dob" timestamp with time zone,
    "gender" text,
    "fcm_token" text,
    "token_version" integer default 0
      );



  create table "public"."extras" (
    "extraid" bigint not null,
    "adminkey" text
      );



  create table "public"."image_entity" (
    "image_entity_id" integer not null,
    "updated_at" timestamp with time zone default now(),
    "entity_category" text,
    "image_id" integer,
    "entity_id" integer,
    "isfeatured" boolean default false,
    "created_at" timestamp with time zone not null default now()
      );



  create table "public"."images" (
    "image_id" integer not null,
    "foldertype" text,
    "filename" text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."inventory_reservations" (
    "reservation_id" character varying not null,
    "variant_id" integer not null,
    "quantity" integer not null,
    "expires_at" timestamp with time zone not null,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."inventory_status" (
    "variant_id" integer,
    "product_name" text,
    "reserved_quantity" bigint,
    "sell_price" numeric,
    "total_stock" integer,
    "available_stock" bigint,
    "variant_name" text
      );



  create table "public"."invoice_coupons" (
    "coupon_id" integer generated always as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "discount_type" text not null,
    "coupon_code" text not null,
    "title" text not null,
    "amount" numeric not null,
    "usage_limit" integer,
    "used_count" integer not null default 0,
    "start_date" timestamp with time zone not null,
    "end_date" timestamp with time zone not null,
    "is_active" boolean not null default true
      );



  create table "public"."notifications" (
    "notification_id" integer not null,
    "product_id" integer,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "isread" boolean default false,
    "expires_at" timestamp with time zone default (now() + '10 days'::interval),
    "order_id" integer,
    "installment_plan_id" integer,
    "description" text,
    "sub_description" text,
    "notificationtype" text
      );



  create table "public"."oauth_users" (
    "id" uuid not null default gen_random_uuid(),
    "google_id" character varying not null,
    "email" character varying not null,
    "name" character varying not null,
    "picture" character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."order_items" (
    "order_id" integer not null,
    "product_id" integer not null,
    "variant_id" integer not null,
    "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "unit" character varying,
    "total_buy_price" numeric default 0.0,
    "quantity" integer not null,
    "price" numeric not null
      );



  create table "public"."orders" (
    "order_id" integer generated always as identity not null,
    "user_id" integer,
    "shipping_method" text,
    "idempotency_key" character varying,
    "buying_price" numeric,
    "discount" numeric default 0.0,
    "tax" numeric default 0.0,
    "shipping_fee" numeric default 0.0,
    "customer_id" integer,
    "payment_method" text default 'cod'::text,
    "salesman_id" integer,
    "salesman_comission" integer,
    "sub_total" numeric not null,
    "status" text not null,
    "address_id" integer,
    "order_date" date not null,
    "paid_amount" numeric,
    "saletype" text
      );



  create table "public"."product_discounts" (
    "discount_id" integer generated always as identity not null,
    "product_id" integer not null,
    "end_date" timestamp with time zone not null,
    "start_date" timestamp with time zone not null,
    "discount_type" text not null,
    "amount" numeric not null,
    "created_at" timestamp with time zone not null default now(),
    "is_active" boolean not null default true
      );



  create table "public"."product_variants" (
    "variant_id" integer not null,
    "sku" character varying,
    "alert_stock" bigint not null default '0'::bigint,
    "stock" integer default 0,
    "is_visible" boolean default true,
    "updated_at" timestamp with time zone default now(),
    "created_at" timestamp with time zone default now(),
    "sell_price" numeric not null,
    "buy_price" numeric not null,
    "product_id" integer not null,
    "variant_name" text not null
      );



  create table "public"."products" (
    "product_id" integer not null,
    "tag" text,
    "description" text default ''::text,
    "name" text not null default ''::text,
    "base_price" text default ''::text,
    "sale_price" text default ''::text,
    "price_range" text default '--'::text,
    "isVisible" boolean default false,
    "alert_stock" integer,
    "brandID" integer default 20,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "stock_quantity" integer default 0,
    "ispopular" boolean default false,
    "category_id" integer default 11
      );



  create table "public"."reviews" (
    "review_id" bigint not null,
    "product_id" integer,
    "customer_id" integer,
    "rating" numeric,
    "review" text default ''::text,
    "sent_at" timestamp with time zone not null default now()
      );



  create table "public"."security_audit_log" (
    "log_id" integer generated always as identity not null,
    "timestamp" timestamp with time zone default now(),
    "user_agent" text,
    "event_type" character varying not null,
    "severity" character varying default 'info'::character varying,
    "event_data" jsonb,
    "customer_id" integer,
    "ip_address" inet
      );



  create table "public"."security_dashboard" (
    "event_type" character varying,
    "severity" character varying,
    "unique_customers" bigint,
    "event_count" bigint,
    "date" date
      );



  create table "public"."shop" (
    "shop_id" integer not null,
    "max_allowed_item_quantity" bigint not null default '50'::bigint,
    "software_website_link" text,
    "software_contact_no" text,
    "software_company_name" text,
    "shopname" text not null,
    "taxrate" numeric not null,
    "shipping_price" numeric not null,
    "threshold_free_shipping" numeric,
    "is_shipping_enable" boolean not null default false
      );



  create table "public"."users" (
    "user_id" integer not null,
    "first_name" text not null default ''::text,
    "gender" text,
    "created_at" timestamp with time zone default (now() AT TIME ZONE 'utc'::text),
    "dob" timestamp with time zone,
    "auth_uid" character varying,
    "email" text not null default ''::text,
    "phone_number" text default ''::text,
    "last_name" text default ''::text
      );



  create table "public"."wishlist" (
    "wishlist_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "product_id" integer,
    "customer_id" integer
      );


CREATE UNIQUE INDEX addresses_pkey ON public.addresses USING btree (address_id);

CREATE UNIQUE INDEX auth_sessions_pkey ON public.auth_sessions USING btree (session_id);

CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree ("brandID");

CREATE UNIQUE INDEX cart_pkey ON public.cart USING btree (cart_id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (category_id);

CREATE UNIQUE INDEX customers_pkey ON public.customers USING btree (customer_id);

CREATE UNIQUE INDEX extras_pkey ON public.extras USING btree (extraid);

CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions USING btree (expires_at);

CREATE INDEX idx_auth_sessions_status ON public.auth_sessions USING btree (status);

CREATE INDEX idx_auth_sessions_user_id ON public.auth_sessions USING btree (user_id);

CREATE INDEX idx_oauth_users_email ON public.oauth_users USING btree (email);

CREATE INDEX idx_oauth_users_google_id ON public.oauth_users USING btree (google_id);

CREATE UNIQUE INDEX image_entity_pkey ON public.image_entity USING btree (image_entity_id);

CREATE UNIQUE INDEX images_pkey ON public.images USING btree (image_id);

CREATE UNIQUE INDEX inventory_reservations_pkey ON public.inventory_reservations USING btree (reservation_id);

CREATE UNIQUE INDEX invoice_coupons_pkey ON public.invoice_coupons USING btree (coupon_id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (notification_id);

CREATE UNIQUE INDEX oauth_users_email_key ON public.oauth_users USING btree (email);

CREATE UNIQUE INDEX oauth_users_google_id_key ON public.oauth_users USING btree (google_id);

CREATE UNIQUE INDEX oauth_users_pkey ON public.oauth_users USING btree (id);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (order_id, product_id, variant_id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (order_id);

CREATE UNIQUE INDEX product_discounts_pkey ON public.product_discounts USING btree (discount_id);

CREATE UNIQUE INDEX product_variants_pkey ON public.product_variants USING btree (variant_id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (review_id);

CREATE UNIQUE INDEX security_audit_log_pkey ON public.security_audit_log USING btree (log_id);

CREATE UNIQUE INDEX shop_pkey ON public.shop USING btree (shop_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

CREATE UNIQUE INDEX wishlist_pkey ON public.wishlist USING btree (wishlist_id);

alter table "public"."addresses" add constraint "addresses_pkey" PRIMARY KEY using index "addresses_pkey";

alter table "public"."auth_sessions" add constraint "auth_sessions_pkey" PRIMARY KEY using index "auth_sessions_pkey";

alter table "public"."brands" add constraint "brands_pkey" PRIMARY KEY using index "brands_pkey";

alter table "public"."cart" add constraint "cart_pkey" PRIMARY KEY using index "cart_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."customers" add constraint "customers_pkey" PRIMARY KEY using index "customers_pkey";

alter table "public"."extras" add constraint "extras_pkey" PRIMARY KEY using index "extras_pkey";

alter table "public"."image_entity" add constraint "image_entity_pkey" PRIMARY KEY using index "image_entity_pkey";

alter table "public"."images" add constraint "images_pkey" PRIMARY KEY using index "images_pkey";

alter table "public"."inventory_reservations" add constraint "inventory_reservations_pkey" PRIMARY KEY using index "inventory_reservations_pkey";

alter table "public"."invoice_coupons" add constraint "invoice_coupons_pkey" PRIMARY KEY using index "invoice_coupons_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."oauth_users" add constraint "oauth_users_pkey" PRIMARY KEY using index "oauth_users_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."product_discounts" add constraint "product_discounts_pkey" PRIMARY KEY using index "product_discounts_pkey";

alter table "public"."product_variants" add constraint "product_variants_pkey" PRIMARY KEY using index "product_variants_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."security_audit_log" add constraint "security_audit_log_pkey" PRIMARY KEY using index "security_audit_log_pkey";

alter table "public"."shop" add constraint "shop_pkey" PRIMARY KEY using index "shop_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."wishlist" add constraint "wishlist_pkey" PRIMARY KEY using index "wishlist_pkey";

alter table "public"."auth_sessions" add constraint "auth_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.oauth_users(id) not valid;

alter table "public"."auth_sessions" validate constraint "auth_sessions_user_id_fkey";

alter table "public"."cart" add constraint "cart_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cart" validate constraint "cart_customer_id_fkey";

alter table "public"."cart" add constraint "cart_variant_id_fkey" FOREIGN KEY (variant_id) REFERENCES public.product_variants(variant_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cart" validate constraint "cart_variant_id_fkey";

alter table "public"."oauth_users" add constraint "oauth_users_email_key" UNIQUE using index "oauth_users_email_key";

alter table "public"."oauth_users" add constraint "oauth_users_google_id_key" UNIQUE using index "oauth_users_google_id_key";

alter table "public"."product_variants" add constraint "product_variants_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(product_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."product_variants" validate constraint "product_variants_product_id_fkey";

grant delete on table "public"."addresses" to "anon";

grant insert on table "public"."addresses" to "anon";

grant references on table "public"."addresses" to "anon";

grant select on table "public"."addresses" to "anon";

grant trigger on table "public"."addresses" to "anon";

grant truncate on table "public"."addresses" to "anon";

grant update on table "public"."addresses" to "anon";

grant delete on table "public"."addresses" to "authenticated";

grant insert on table "public"."addresses" to "authenticated";

grant references on table "public"."addresses" to "authenticated";

grant select on table "public"."addresses" to "authenticated";

grant trigger on table "public"."addresses" to "authenticated";

grant truncate on table "public"."addresses" to "authenticated";

grant update on table "public"."addresses" to "authenticated";

grant delete on table "public"."addresses" to "postgres";

grant insert on table "public"."addresses" to "postgres";

grant references on table "public"."addresses" to "postgres";

grant select on table "public"."addresses" to "postgres";

grant trigger on table "public"."addresses" to "postgres";

grant truncate on table "public"."addresses" to "postgres";

grant update on table "public"."addresses" to "postgres";

grant delete on table "public"."addresses" to "service_role";

grant insert on table "public"."addresses" to "service_role";

grant references on table "public"."addresses" to "service_role";

grant select on table "public"."addresses" to "service_role";

grant trigger on table "public"."addresses" to "service_role";

grant truncate on table "public"."addresses" to "service_role";

grant update on table "public"."addresses" to "service_role";

grant delete on table "public"."auth_sessions" to "anon";

grant insert on table "public"."auth_sessions" to "anon";

grant references on table "public"."auth_sessions" to "anon";

grant select on table "public"."auth_sessions" to "anon";

grant trigger on table "public"."auth_sessions" to "anon";

grant truncate on table "public"."auth_sessions" to "anon";

grant update on table "public"."auth_sessions" to "anon";

grant delete on table "public"."auth_sessions" to "authenticated";

grant insert on table "public"."auth_sessions" to "authenticated";

grant references on table "public"."auth_sessions" to "authenticated";

grant select on table "public"."auth_sessions" to "authenticated";

grant trigger on table "public"."auth_sessions" to "authenticated";

grant truncate on table "public"."auth_sessions" to "authenticated";

grant update on table "public"."auth_sessions" to "authenticated";

grant delete on table "public"."auth_sessions" to "postgres";

grant insert on table "public"."auth_sessions" to "postgres";

grant references on table "public"."auth_sessions" to "postgres";

grant select on table "public"."auth_sessions" to "postgres";

grant trigger on table "public"."auth_sessions" to "postgres";

grant truncate on table "public"."auth_sessions" to "postgres";

grant update on table "public"."auth_sessions" to "postgres";

grant delete on table "public"."auth_sessions" to "service_role";

grant insert on table "public"."auth_sessions" to "service_role";

grant references on table "public"."auth_sessions" to "service_role";

grant select on table "public"."auth_sessions" to "service_role";

grant trigger on table "public"."auth_sessions" to "service_role";

grant truncate on table "public"."auth_sessions" to "service_role";

grant update on table "public"."auth_sessions" to "service_role";

grant delete on table "public"."brands" to "anon";

grant insert on table "public"."brands" to "anon";

grant references on table "public"."brands" to "anon";

grant select on table "public"."brands" to "anon";

grant trigger on table "public"."brands" to "anon";

grant truncate on table "public"."brands" to "anon";

grant update on table "public"."brands" to "anon";

grant delete on table "public"."brands" to "authenticated";

grant insert on table "public"."brands" to "authenticated";

grant references on table "public"."brands" to "authenticated";

grant select on table "public"."brands" to "authenticated";

grant trigger on table "public"."brands" to "authenticated";

grant truncate on table "public"."brands" to "authenticated";

grant update on table "public"."brands" to "authenticated";

grant delete on table "public"."brands" to "postgres";

grant insert on table "public"."brands" to "postgres";

grant references on table "public"."brands" to "postgres";

grant select on table "public"."brands" to "postgres";

grant trigger on table "public"."brands" to "postgres";

grant truncate on table "public"."brands" to "postgres";

grant update on table "public"."brands" to "postgres";

grant delete on table "public"."brands" to "service_role";

grant insert on table "public"."brands" to "service_role";

grant references on table "public"."brands" to "service_role";

grant select on table "public"."brands" to "service_role";

grant trigger on table "public"."brands" to "service_role";

grant truncate on table "public"."brands" to "service_role";

grant update on table "public"."brands" to "service_role";

grant delete on table "public"."cart" to "anon";

grant insert on table "public"."cart" to "anon";

grant references on table "public"."cart" to "anon";

grant select on table "public"."cart" to "anon";

grant trigger on table "public"."cart" to "anon";

grant truncate on table "public"."cart" to "anon";

grant update on table "public"."cart" to "anon";

grant delete on table "public"."cart" to "authenticated";

grant insert on table "public"."cart" to "authenticated";

grant references on table "public"."cart" to "authenticated";

grant select on table "public"."cart" to "authenticated";

grant trigger on table "public"."cart" to "authenticated";

grant truncate on table "public"."cart" to "authenticated";

grant update on table "public"."cart" to "authenticated";

grant delete on table "public"."cart" to "postgres";

grant insert on table "public"."cart" to "postgres";

grant references on table "public"."cart" to "postgres";

grant select on table "public"."cart" to "postgres";

grant trigger on table "public"."cart" to "postgres";

grant truncate on table "public"."cart" to "postgres";

grant update on table "public"."cart" to "postgres";

grant delete on table "public"."cart" to "service_role";

grant insert on table "public"."cart" to "service_role";

grant references on table "public"."cart" to "service_role";

grant select on table "public"."cart" to "service_role";

grant trigger on table "public"."cart" to "service_role";

grant truncate on table "public"."cart" to "service_role";

grant update on table "public"."cart" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "postgres";

grant insert on table "public"."categories" to "postgres";

grant references on table "public"."categories" to "postgres";

grant select on table "public"."categories" to "postgres";

grant trigger on table "public"."categories" to "postgres";

grant truncate on table "public"."categories" to "postgres";

grant update on table "public"."categories" to "postgres";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."customers" to "anon";

grant insert on table "public"."customers" to "anon";

grant references on table "public"."customers" to "anon";

grant select on table "public"."customers" to "anon";

grant trigger on table "public"."customers" to "anon";

grant truncate on table "public"."customers" to "anon";

grant update on table "public"."customers" to "anon";

grant delete on table "public"."customers" to "authenticated";

grant insert on table "public"."customers" to "authenticated";

grant references on table "public"."customers" to "authenticated";

grant select on table "public"."customers" to "authenticated";

grant trigger on table "public"."customers" to "authenticated";

grant truncate on table "public"."customers" to "authenticated";

grant update on table "public"."customers" to "authenticated";

grant delete on table "public"."customers" to "postgres";

grant insert on table "public"."customers" to "postgres";

grant references on table "public"."customers" to "postgres";

grant select on table "public"."customers" to "postgres";

grant trigger on table "public"."customers" to "postgres";

grant truncate on table "public"."customers" to "postgres";

grant update on table "public"."customers" to "postgres";

grant delete on table "public"."customers" to "service_role";

grant insert on table "public"."customers" to "service_role";

grant references on table "public"."customers" to "service_role";

grant select on table "public"."customers" to "service_role";

grant trigger on table "public"."customers" to "service_role";

grant truncate on table "public"."customers" to "service_role";

grant update on table "public"."customers" to "service_role";

grant delete on table "public"."extras" to "anon";

grant insert on table "public"."extras" to "anon";

grant references on table "public"."extras" to "anon";

grant select on table "public"."extras" to "anon";

grant trigger on table "public"."extras" to "anon";

grant truncate on table "public"."extras" to "anon";

grant update on table "public"."extras" to "anon";

grant delete on table "public"."extras" to "authenticated";

grant insert on table "public"."extras" to "authenticated";

grant references on table "public"."extras" to "authenticated";

grant select on table "public"."extras" to "authenticated";

grant trigger on table "public"."extras" to "authenticated";

grant truncate on table "public"."extras" to "authenticated";

grant update on table "public"."extras" to "authenticated";

grant delete on table "public"."extras" to "postgres";

grant insert on table "public"."extras" to "postgres";

grant references on table "public"."extras" to "postgres";

grant select on table "public"."extras" to "postgres";

grant trigger on table "public"."extras" to "postgres";

grant truncate on table "public"."extras" to "postgres";

grant update on table "public"."extras" to "postgres";

grant delete on table "public"."extras" to "service_role";

grant insert on table "public"."extras" to "service_role";

grant references on table "public"."extras" to "service_role";

grant select on table "public"."extras" to "service_role";

grant trigger on table "public"."extras" to "service_role";

grant truncate on table "public"."extras" to "service_role";

grant update on table "public"."extras" to "service_role";

grant delete on table "public"."image_entity" to "anon";

grant insert on table "public"."image_entity" to "anon";

grant references on table "public"."image_entity" to "anon";

grant select on table "public"."image_entity" to "anon";

grant trigger on table "public"."image_entity" to "anon";

grant truncate on table "public"."image_entity" to "anon";

grant update on table "public"."image_entity" to "anon";

grant delete on table "public"."image_entity" to "authenticated";

grant insert on table "public"."image_entity" to "authenticated";

grant references on table "public"."image_entity" to "authenticated";

grant select on table "public"."image_entity" to "authenticated";

grant trigger on table "public"."image_entity" to "authenticated";

grant truncate on table "public"."image_entity" to "authenticated";

grant update on table "public"."image_entity" to "authenticated";

grant delete on table "public"."image_entity" to "postgres";

grant insert on table "public"."image_entity" to "postgres";

grant references on table "public"."image_entity" to "postgres";

grant select on table "public"."image_entity" to "postgres";

grant trigger on table "public"."image_entity" to "postgres";

grant truncate on table "public"."image_entity" to "postgres";

grant update on table "public"."image_entity" to "postgres";

grant delete on table "public"."image_entity" to "service_role";

grant insert on table "public"."image_entity" to "service_role";

grant references on table "public"."image_entity" to "service_role";

grant select on table "public"."image_entity" to "service_role";

grant trigger on table "public"."image_entity" to "service_role";

grant truncate on table "public"."image_entity" to "service_role";

grant update on table "public"."image_entity" to "service_role";

grant delete on table "public"."images" to "anon";

grant insert on table "public"."images" to "anon";

grant references on table "public"."images" to "anon";

grant select on table "public"."images" to "anon";

grant trigger on table "public"."images" to "anon";

grant truncate on table "public"."images" to "anon";

grant update on table "public"."images" to "anon";

grant delete on table "public"."images" to "authenticated";

grant insert on table "public"."images" to "authenticated";

grant references on table "public"."images" to "authenticated";

grant select on table "public"."images" to "authenticated";

grant trigger on table "public"."images" to "authenticated";

grant truncate on table "public"."images" to "authenticated";

grant update on table "public"."images" to "authenticated";

grant delete on table "public"."images" to "postgres";

grant insert on table "public"."images" to "postgres";

grant references on table "public"."images" to "postgres";

grant select on table "public"."images" to "postgres";

grant trigger on table "public"."images" to "postgres";

grant truncate on table "public"."images" to "postgres";

grant update on table "public"."images" to "postgres";

grant delete on table "public"."images" to "service_role";

grant insert on table "public"."images" to "service_role";

grant references on table "public"."images" to "service_role";

grant select on table "public"."images" to "service_role";

grant trigger on table "public"."images" to "service_role";

grant truncate on table "public"."images" to "service_role";

grant update on table "public"."images" to "service_role";

grant delete on table "public"."inventory_reservations" to "anon";

grant insert on table "public"."inventory_reservations" to "anon";

grant references on table "public"."inventory_reservations" to "anon";

grant select on table "public"."inventory_reservations" to "anon";

grant trigger on table "public"."inventory_reservations" to "anon";

grant truncate on table "public"."inventory_reservations" to "anon";

grant update on table "public"."inventory_reservations" to "anon";

grant delete on table "public"."inventory_reservations" to "authenticated";

grant insert on table "public"."inventory_reservations" to "authenticated";

grant references on table "public"."inventory_reservations" to "authenticated";

grant select on table "public"."inventory_reservations" to "authenticated";

grant trigger on table "public"."inventory_reservations" to "authenticated";

grant truncate on table "public"."inventory_reservations" to "authenticated";

grant update on table "public"."inventory_reservations" to "authenticated";

grant delete on table "public"."inventory_reservations" to "postgres";

grant insert on table "public"."inventory_reservations" to "postgres";

grant references on table "public"."inventory_reservations" to "postgres";

grant select on table "public"."inventory_reservations" to "postgres";

grant trigger on table "public"."inventory_reservations" to "postgres";

grant truncate on table "public"."inventory_reservations" to "postgres";

grant update on table "public"."inventory_reservations" to "postgres";

grant delete on table "public"."inventory_reservations" to "service_role";

grant insert on table "public"."inventory_reservations" to "service_role";

grant references on table "public"."inventory_reservations" to "service_role";

grant select on table "public"."inventory_reservations" to "service_role";

grant trigger on table "public"."inventory_reservations" to "service_role";

grant truncate on table "public"."inventory_reservations" to "service_role";

grant update on table "public"."inventory_reservations" to "service_role";

grant delete on table "public"."inventory_status" to "anon";

grant insert on table "public"."inventory_status" to "anon";

grant references on table "public"."inventory_status" to "anon";

grant select on table "public"."inventory_status" to "anon";

grant trigger on table "public"."inventory_status" to "anon";

grant truncate on table "public"."inventory_status" to "anon";

grant update on table "public"."inventory_status" to "anon";

grant delete on table "public"."inventory_status" to "authenticated";

grant insert on table "public"."inventory_status" to "authenticated";

grant references on table "public"."inventory_status" to "authenticated";

grant select on table "public"."inventory_status" to "authenticated";

grant trigger on table "public"."inventory_status" to "authenticated";

grant truncate on table "public"."inventory_status" to "authenticated";

grant update on table "public"."inventory_status" to "authenticated";

grant delete on table "public"."inventory_status" to "postgres";

grant insert on table "public"."inventory_status" to "postgres";

grant references on table "public"."inventory_status" to "postgres";

grant select on table "public"."inventory_status" to "postgres";

grant trigger on table "public"."inventory_status" to "postgres";

grant truncate on table "public"."inventory_status" to "postgres";

grant update on table "public"."inventory_status" to "postgres";

grant delete on table "public"."inventory_status" to "service_role";

grant insert on table "public"."inventory_status" to "service_role";

grant references on table "public"."inventory_status" to "service_role";

grant select on table "public"."inventory_status" to "service_role";

grant trigger on table "public"."inventory_status" to "service_role";

grant truncate on table "public"."inventory_status" to "service_role";

grant update on table "public"."inventory_status" to "service_role";

grant delete on table "public"."invoice_coupons" to "anon";

grant insert on table "public"."invoice_coupons" to "anon";

grant references on table "public"."invoice_coupons" to "anon";

grant select on table "public"."invoice_coupons" to "anon";

grant trigger on table "public"."invoice_coupons" to "anon";

grant truncate on table "public"."invoice_coupons" to "anon";

grant update on table "public"."invoice_coupons" to "anon";

grant delete on table "public"."invoice_coupons" to "authenticated";

grant insert on table "public"."invoice_coupons" to "authenticated";

grant references on table "public"."invoice_coupons" to "authenticated";

grant select on table "public"."invoice_coupons" to "authenticated";

grant trigger on table "public"."invoice_coupons" to "authenticated";

grant truncate on table "public"."invoice_coupons" to "authenticated";

grant update on table "public"."invoice_coupons" to "authenticated";

grant delete on table "public"."invoice_coupons" to "postgres";

grant insert on table "public"."invoice_coupons" to "postgres";

grant references on table "public"."invoice_coupons" to "postgres";

grant select on table "public"."invoice_coupons" to "postgres";

grant trigger on table "public"."invoice_coupons" to "postgres";

grant truncate on table "public"."invoice_coupons" to "postgres";

grant update on table "public"."invoice_coupons" to "postgres";

grant delete on table "public"."invoice_coupons" to "service_role";

grant insert on table "public"."invoice_coupons" to "service_role";

grant references on table "public"."invoice_coupons" to "service_role";

grant select on table "public"."invoice_coupons" to "service_role";

grant trigger on table "public"."invoice_coupons" to "service_role";

grant truncate on table "public"."invoice_coupons" to "service_role";

grant update on table "public"."invoice_coupons" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "postgres";

grant insert on table "public"."notifications" to "postgres";

grant references on table "public"."notifications" to "postgres";

grant select on table "public"."notifications" to "postgres";

grant trigger on table "public"."notifications" to "postgres";

grant truncate on table "public"."notifications" to "postgres";

grant update on table "public"."notifications" to "postgres";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."oauth_users" to "anon";

grant insert on table "public"."oauth_users" to "anon";

grant references on table "public"."oauth_users" to "anon";

grant select on table "public"."oauth_users" to "anon";

grant trigger on table "public"."oauth_users" to "anon";

grant truncate on table "public"."oauth_users" to "anon";

grant update on table "public"."oauth_users" to "anon";

grant delete on table "public"."oauth_users" to "authenticated";

grant insert on table "public"."oauth_users" to "authenticated";

grant references on table "public"."oauth_users" to "authenticated";

grant select on table "public"."oauth_users" to "authenticated";

grant trigger on table "public"."oauth_users" to "authenticated";

grant truncate on table "public"."oauth_users" to "authenticated";

grant update on table "public"."oauth_users" to "authenticated";

grant delete on table "public"."oauth_users" to "postgres";

grant insert on table "public"."oauth_users" to "postgres";

grant references on table "public"."oauth_users" to "postgres";

grant select on table "public"."oauth_users" to "postgres";

grant trigger on table "public"."oauth_users" to "postgres";

grant truncate on table "public"."oauth_users" to "postgres";

grant update on table "public"."oauth_users" to "postgres";

grant delete on table "public"."oauth_users" to "service_role";

grant insert on table "public"."oauth_users" to "service_role";

grant references on table "public"."oauth_users" to "service_role";

grant select on table "public"."oauth_users" to "service_role";

grant trigger on table "public"."oauth_users" to "service_role";

grant truncate on table "public"."oauth_users" to "service_role";

grant update on table "public"."oauth_users" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "postgres";

grant insert on table "public"."order_items" to "postgres";

grant references on table "public"."order_items" to "postgres";

grant select on table "public"."order_items" to "postgres";

grant trigger on table "public"."order_items" to "postgres";

grant truncate on table "public"."order_items" to "postgres";

grant update on table "public"."order_items" to "postgres";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "postgres";

grant insert on table "public"."orders" to "postgres";

grant references on table "public"."orders" to "postgres";

grant select on table "public"."orders" to "postgres";

grant trigger on table "public"."orders" to "postgres";

grant truncate on table "public"."orders" to "postgres";

grant update on table "public"."orders" to "postgres";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."product_discounts" to "anon";

grant insert on table "public"."product_discounts" to "anon";

grant references on table "public"."product_discounts" to "anon";

grant select on table "public"."product_discounts" to "anon";

grant trigger on table "public"."product_discounts" to "anon";

grant truncate on table "public"."product_discounts" to "anon";

grant update on table "public"."product_discounts" to "anon";

grant delete on table "public"."product_discounts" to "authenticated";

grant insert on table "public"."product_discounts" to "authenticated";

grant references on table "public"."product_discounts" to "authenticated";

grant select on table "public"."product_discounts" to "authenticated";

grant trigger on table "public"."product_discounts" to "authenticated";

grant truncate on table "public"."product_discounts" to "authenticated";

grant update on table "public"."product_discounts" to "authenticated";

grant delete on table "public"."product_discounts" to "postgres";

grant insert on table "public"."product_discounts" to "postgres";

grant references on table "public"."product_discounts" to "postgres";

grant select on table "public"."product_discounts" to "postgres";

grant trigger on table "public"."product_discounts" to "postgres";

grant truncate on table "public"."product_discounts" to "postgres";

grant update on table "public"."product_discounts" to "postgres";

grant delete on table "public"."product_discounts" to "service_role";

grant insert on table "public"."product_discounts" to "service_role";

grant references on table "public"."product_discounts" to "service_role";

grant select on table "public"."product_discounts" to "service_role";

grant trigger on table "public"."product_discounts" to "service_role";

grant truncate on table "public"."product_discounts" to "service_role";

grant update on table "public"."product_discounts" to "service_role";

grant delete on table "public"."product_variants" to "anon";

grant insert on table "public"."product_variants" to "anon";

grant references on table "public"."product_variants" to "anon";

grant select on table "public"."product_variants" to "anon";

grant trigger on table "public"."product_variants" to "anon";

grant truncate on table "public"."product_variants" to "anon";

grant update on table "public"."product_variants" to "anon";

grant delete on table "public"."product_variants" to "authenticated";

grant insert on table "public"."product_variants" to "authenticated";

grant references on table "public"."product_variants" to "authenticated";

grant select on table "public"."product_variants" to "authenticated";

grant trigger on table "public"."product_variants" to "authenticated";

grant truncate on table "public"."product_variants" to "authenticated";

grant update on table "public"."product_variants" to "authenticated";

grant delete on table "public"."product_variants" to "postgres";

grant insert on table "public"."product_variants" to "postgres";

grant references on table "public"."product_variants" to "postgres";

grant select on table "public"."product_variants" to "postgres";

grant trigger on table "public"."product_variants" to "postgres";

grant truncate on table "public"."product_variants" to "postgres";

grant update on table "public"."product_variants" to "postgres";

grant delete on table "public"."product_variants" to "service_role";

grant insert on table "public"."product_variants" to "service_role";

grant references on table "public"."product_variants" to "service_role";

grant select on table "public"."product_variants" to "service_role";

grant trigger on table "public"."product_variants" to "service_role";

grant truncate on table "public"."product_variants" to "service_role";

grant update on table "public"."product_variants" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "postgres";

grant insert on table "public"."products" to "postgres";

grant references on table "public"."products" to "postgres";

grant select on table "public"."products" to "postgres";

grant trigger on table "public"."products" to "postgres";

grant truncate on table "public"."products" to "postgres";

grant update on table "public"."products" to "postgres";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "postgres";

grant insert on table "public"."reviews" to "postgres";

grant references on table "public"."reviews" to "postgres";

grant select on table "public"."reviews" to "postgres";

grant trigger on table "public"."reviews" to "postgres";

grant truncate on table "public"."reviews" to "postgres";

grant update on table "public"."reviews" to "postgres";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."security_audit_log" to "anon";

grant insert on table "public"."security_audit_log" to "anon";

grant references on table "public"."security_audit_log" to "anon";

grant select on table "public"."security_audit_log" to "anon";

grant trigger on table "public"."security_audit_log" to "anon";

grant truncate on table "public"."security_audit_log" to "anon";

grant update on table "public"."security_audit_log" to "anon";

grant delete on table "public"."security_audit_log" to "authenticated";

grant insert on table "public"."security_audit_log" to "authenticated";

grant references on table "public"."security_audit_log" to "authenticated";

grant select on table "public"."security_audit_log" to "authenticated";

grant trigger on table "public"."security_audit_log" to "authenticated";

grant truncate on table "public"."security_audit_log" to "authenticated";

grant update on table "public"."security_audit_log" to "authenticated";

grant delete on table "public"."security_audit_log" to "postgres";

grant insert on table "public"."security_audit_log" to "postgres";

grant references on table "public"."security_audit_log" to "postgres";

grant select on table "public"."security_audit_log" to "postgres";

grant trigger on table "public"."security_audit_log" to "postgres";

grant truncate on table "public"."security_audit_log" to "postgres";

grant update on table "public"."security_audit_log" to "postgres";

grant delete on table "public"."security_audit_log" to "service_role";

grant insert on table "public"."security_audit_log" to "service_role";

grant references on table "public"."security_audit_log" to "service_role";

grant select on table "public"."security_audit_log" to "service_role";

grant trigger on table "public"."security_audit_log" to "service_role";

grant truncate on table "public"."security_audit_log" to "service_role";

grant update on table "public"."security_audit_log" to "service_role";

grant delete on table "public"."security_dashboard" to "anon";

grant insert on table "public"."security_dashboard" to "anon";

grant references on table "public"."security_dashboard" to "anon";

grant select on table "public"."security_dashboard" to "anon";

grant trigger on table "public"."security_dashboard" to "anon";

grant truncate on table "public"."security_dashboard" to "anon";

grant update on table "public"."security_dashboard" to "anon";

grant delete on table "public"."security_dashboard" to "authenticated";

grant insert on table "public"."security_dashboard" to "authenticated";

grant references on table "public"."security_dashboard" to "authenticated";

grant select on table "public"."security_dashboard" to "authenticated";

grant trigger on table "public"."security_dashboard" to "authenticated";

grant truncate on table "public"."security_dashboard" to "authenticated";

grant update on table "public"."security_dashboard" to "authenticated";

grant delete on table "public"."security_dashboard" to "postgres";

grant insert on table "public"."security_dashboard" to "postgres";

grant references on table "public"."security_dashboard" to "postgres";

grant select on table "public"."security_dashboard" to "postgres";

grant trigger on table "public"."security_dashboard" to "postgres";

grant truncate on table "public"."security_dashboard" to "postgres";

grant update on table "public"."security_dashboard" to "postgres";

grant delete on table "public"."security_dashboard" to "service_role";

grant insert on table "public"."security_dashboard" to "service_role";

grant references on table "public"."security_dashboard" to "service_role";

grant select on table "public"."security_dashboard" to "service_role";

grant trigger on table "public"."security_dashboard" to "service_role";

grant truncate on table "public"."security_dashboard" to "service_role";

grant update on table "public"."security_dashboard" to "service_role";

grant delete on table "public"."shop" to "anon";

grant insert on table "public"."shop" to "anon";

grant references on table "public"."shop" to "anon";

grant select on table "public"."shop" to "anon";

grant trigger on table "public"."shop" to "anon";

grant truncate on table "public"."shop" to "anon";

grant update on table "public"."shop" to "anon";

grant delete on table "public"."shop" to "authenticated";

grant insert on table "public"."shop" to "authenticated";

grant references on table "public"."shop" to "authenticated";

grant select on table "public"."shop" to "authenticated";

grant trigger on table "public"."shop" to "authenticated";

grant truncate on table "public"."shop" to "authenticated";

grant update on table "public"."shop" to "authenticated";

grant delete on table "public"."shop" to "postgres";

grant insert on table "public"."shop" to "postgres";

grant references on table "public"."shop" to "postgres";

grant select on table "public"."shop" to "postgres";

grant trigger on table "public"."shop" to "postgres";

grant truncate on table "public"."shop" to "postgres";

grant update on table "public"."shop" to "postgres";

grant delete on table "public"."shop" to "service_role";

grant insert on table "public"."shop" to "service_role";

grant references on table "public"."shop" to "service_role";

grant select on table "public"."shop" to "service_role";

grant trigger on table "public"."shop" to "service_role";

grant truncate on table "public"."shop" to "service_role";

grant update on table "public"."shop" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "postgres";

grant insert on table "public"."users" to "postgres";

grant references on table "public"."users" to "postgres";

grant select on table "public"."users" to "postgres";

grant trigger on table "public"."users" to "postgres";

grant truncate on table "public"."users" to "postgres";

grant update on table "public"."users" to "postgres";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."wishlist" to "anon";

grant insert on table "public"."wishlist" to "anon";

grant references on table "public"."wishlist" to "anon";

grant select on table "public"."wishlist" to "anon";

grant trigger on table "public"."wishlist" to "anon";

grant truncate on table "public"."wishlist" to "anon";

grant update on table "public"."wishlist" to "anon";

grant delete on table "public"."wishlist" to "authenticated";

grant insert on table "public"."wishlist" to "authenticated";

grant references on table "public"."wishlist" to "authenticated";

grant select on table "public"."wishlist" to "authenticated";

grant trigger on table "public"."wishlist" to "authenticated";

grant truncate on table "public"."wishlist" to "authenticated";

grant update on table "public"."wishlist" to "authenticated";

grant delete on table "public"."wishlist" to "postgres";

grant insert on table "public"."wishlist" to "postgres";

grant references on table "public"."wishlist" to "postgres";

grant select on table "public"."wishlist" to "postgres";

grant trigger on table "public"."wishlist" to "postgres";

grant truncate on table "public"."wishlist" to "postgres";

grant update on table "public"."wishlist" to "postgres";

grant delete on table "public"."wishlist" to "service_role";

grant insert on table "public"."wishlist" to "service_role";

grant references on table "public"."wishlist" to "service_role";

grant select on table "public"."wishlist" to "service_role";

grant trigger on table "public"."wishlist" to "service_role";

grant truncate on table "public"."wishlist" to "service_role";

grant update on table "public"."wishlist" to "service_role";

DROP TRIGGER IF EXISTS objects_delete_delete_prefix ON storage.objects;
CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

DROP TRIGGER IF EXISTS objects_insert_create_prefix ON storage.objects;
CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

DROP TRIGGER IF EXISTS objects_update_create_prefix ON storage.objects;
CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

DROP TRIGGER IF EXISTS prefixes_create_hierarchy ON storage.prefixes;
CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

DROP TRIGGER IF EXISTS prefixes_delete_hierarchy ON storage.prefixes;
CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();



